### ISSUE TITLE
Some published dates are missing

### ISSUE THREAD

**Issue by MatBenfield** [MatBenfield/morning.thechels.uk#4]
As a user I would like all the articles to include a published date so that I can be assured if the article is new.

This might be because its not valid in the RSS feed - I've seen PubDate used too.
perhaps a try catch is needed?

**Comment by darensin01** [comment]
Hi, I'm trying to solve this problem in #7. Let me know if I'm missing anything! Basically, I'm using [this library](https://datefinder.readthedocs.io/en/latest/) to infer the date for the entry, instead of using "T" to split the datetime. This produces a datetime object which can then be parsed into a standardised datetime format. If there's no datetime to infer for some reason, the datetime string will be empty.
